export const CREATE_STUDENT= "CREATE_STUDENT";
export const LOAD_STUDENTS_SUCCESS = "LOAD_STUDENTS_SUCCESS";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const LOAD_BRANCHES_SUCCESS = "LOAD_BRANCHES_SUCCESS";
